// Generated by CoffeeScript 1.3.1
(function() {
  var Ping, ping;

  Ping = require('./ping');

  ping = new Ping('google.com');

  ping.on('data', function(data) {
    return console.log(data);
  });

  ping.on('exit', function(data) {
    return console.log(data);
  });

}).call(this);
